#Simple workfow to build CoreELEC Docker for Phicomm N1
name: build coreelec docker for n1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the n1-19 branch
  push:
    branches: [ n1-19 ]
  pull_request:
    branches: [ n1-19 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip dpkg dpkg-deb dpkg-split libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
         - name: Run build
        run: ./compile-docker.bash buildx -a arm64
        
         - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: docker_for_n1
          path: ./docker*.tar.gz
      
