name: build coreelec docker for n1

on:
  push:
    branches: [ n1-19 ]
  pull_request:
    branches: [ n1-19 ]
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Initialization Environment
        run: |
          echo $CUSTOM_VERSION
          git branch -v
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/share/man
          sudo -E apt-get -qq update
          sudo -E apt-get install gcc make git unzip wget xz-utils bc gperf zip unzip g++  build-essential patchutils lzop xfonts-utils xsltproc libjson-perl cmake texinfo default-jre libncurses5-dev file zstd libparse-yapp-perl
          sudo -E apt-get -qq autoremove --purge
      - name: Run build
        run: ./compile-docker.bash
      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: docker_download
          path: ./docker*.tar.gz      
